image: haskell:8.4.4

pipelines:
  branches:
    master:
      - step:
          script:
            - cabal new-build
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"`find dist-newstyle -type f -name scpecg`"
