#!/bin/sh

recpid=$1
shift

echo "preparing to play, args $*"
sleep 1
echo "starting to play"
`dirname $0`/playecg $*
echo "finished playing"
sleep 1
echo "killing `cat $recpid`"
kill -INT `cat $recpid`
sleep 1
echo "returning from play"
